# Generated by Django 6.0 on 2025-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='opinion',
            field=models.TextField(verbose_name='Opinião'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota'),
        ),
    ]
