# Generated by Django 5.2.8 on 2025-11-28 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_gameid_game_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likegame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='likegame',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteGame',
        ),
        migrations.DeleteModel(
            name='LikeGame',
        ),
    ]
