# Generated by Django 5.2.8 on 2025-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
