# Generated by Django 6.0 on 2025-12-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelistitem',
            name='note',
        ),
    ]
