# Generated by Django 6.0 on 2025-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_gamelistitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='É público'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
